InsertKoinIO/koin-annotations

- README.md
- quickstart/quickstart-android-annotations/app/build.gradle
Using `configureEach` instead of `all` is much better. It's not required to clean project between flavor changes anymore.
> Fix source set configuration

- Documentation.md
> To define a definition directly in your **scan**, you an annotate a function with definition annotations:
> Correct spelling: can → scan

- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/KoinScanner.kt
This PR objective is to add basic support for KSP Multiple Round Processing. (https://kotlinlang.org/docs/ksp-multi-round.html)
The issue it tries to solve is that if the Koin Compiler is used alongside another KSP-based compiler, Koin may generate incomplete module code. For instance if a class annotated for Koin requires the result of another compiler to become "valid".
The contract of a `SymbolProcessor` states thaf if it returns a List of invalid annotated entites, KSP will re-call the processor later, including any code generated by other processors during round one.
To achieve that, the `KoinMetaDataScanner` job was split in two parts.
1. It scans for module and definition symbols. If it finds any invalid entity, it returns the list and the processing ends there. All valid entites …
> Added basic support for Multiple Round Processing

- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/ModuleGenerationExt.kt
- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/Utils.kt
- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/KoinMetaData.kt
- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/ModuleScanner.kt
Generated module fields and extension properties always have (implicit) public visibility.
If a module class has `internal` visibility, this causes an `'public' member exposes its 'internal' receiver type <type>` compiler error
Explicitly add the visibility of the module class to the generated field and extension property.
> Preserve module visibility

- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinGenerator.kt
This PR removes the "stop processing" flag since there might be some code to process that was not available in the first round of ksp processing.
For example: Koin was able to successfully do a first round, where the compiler found `@Module` and `@ComponentScan`. The code was generated and the `codeGenerated` flag was set to true. The issue is that some other ksp processor did generate a new class during the first round. The new class has `@Single` annotation, but it was ignored since the `codeGenerated` flag was shutting further processing down.
This fix makes the processor able to do multiple rounds on the same symbols and recreating generated modules file contents if necessary.
Fixes #66
> Fix multiple round pass issue #66

- README.md
- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/KoinMetaDataScanner.kt
- sandbox/android-coffee-maker/build.gradle.kts
- sandbox/android-library/build.gradle.kts
Valid symbols must be kept between rounds since they won't be sent again by KSP.
This was accidentally broken in a cleanup commit: https://github.com/InsertKoinIO/koin-annotations/commit/b386438a740219e0b456b8928463b816e617babc
When returning some invalid entities to KSP for next processing round, it is important to keep the valid ones, since during next round only new and previously invalid entities will be provided by KSP. 
@jakoss You may be interested / have an opinion, since you did some changes in that section too.
> Fixed multiple round processing

- compiler/koin-annotations/src/commonMain/kotlin/org/koin/core/annotation/CoreAnnotations.kt
- compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/KspExt.kt
- sandbox/android-coffee-maker/build.gradle.kts
- sandbox/android-library/build.gradle.kts
I'm doing a little bit of processing in another project and when i try to pass the `AnnotationSpec` of koin `Scope` annotation i get an error that i cannot use private class as a default value of a parameter in annotation. Since we can use `Unit` just fine in this place it seems like an easy and safe change
> Use Unit::class as a default value of KClass parameter in annotation

- examples/android-coffee-maker/build.gradle.kts
- examples/android-coffee-maker/src/test/java/AndroidModuleTest.kt
- examples/android-library/build.gradle.kts
- examples/android-library/src/main/java/org/koin/sample/androidx/data/DataConsumer.kt
- examples/coffee-maker-module/src/main/kotlin/org/koin/example/coffee/DetachedComponents.kt
- examples/coffee-maker/build.gradle.kts
- examples/coffee-maker/src/test/java/CoffeeAppTest.kt
- projects/koin-annotations/src/commonMain/kotlin/org/koin/core/annotation/CoreAnnotations.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/DefinitionGenerationExt.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinGenerator.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/ModuleGenerationExt.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/Templates.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/KoinMetaData.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/KoinMetaDataScanner.kt
Generate definitions as external if not captured in a local module, to be scanned by an external module later.
Those external definitions are functions, that can be called in other modules. They are generated in Default file, where it can be imported via @Definition annotation. 
Examples apps are updated with such use. Like:
```kotlin
package org.koin.sample.androidx.data
@Factory
class DataConsumer
```
will be scanned by in another Gradle module:
```kotlin
@ComponentScan("org.koin.sample.androidx.data")
class DataModule
```
Generated code in Default file, to be scanner by compiler:
```kotlin
@Definition("org.koin.sample.androidx.data")
fun Module.defineDataConsumer() = factory() { org.koin.sample.androidx.data.DataConsumer() } 
```
> Multimodule scan for definitions

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/KspOptions.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinGenerator.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/ModuleGenerationExt.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/AnnotationMetadata.kt
Allow to generate Compose KMP ViewModel definition instead of default Android.
For this, we need a temporary argument, while Koin 4 will bring a common ViewModel DSL for that.
```kotlin
ksp {
arg("USE_COMPOSE_VIEWMODEL","true")
}
```
> USE_COMPOSE_VIEWMODEL  arg to generate Viewmodel for compose (Compose DSL API)

- examples/android-coffee-maker/build.gradle.kts
- examples/android-coffee-maker/src/main/java/org/koin/sample/androidx/MainActivity.kt
- examples/android-coffee-maker/src/main/java/org/koin/sample/androidx/app/MyPresenter.kt
- examples/android-coffee-maker/src/main/java/org/koin/sample/androidx/data/ProvidedComponent.kt
- examples/android-coffee-maker/src/test/java/AndroidModuleTest.kt
- examples/android-library/build.gradle.kts
- projects/koin-annotations/src/commonMain/kotlin/org/koin/android/annotation/AndroidAnnotations.kt
- projects/koin-annotations/src/commonMain/kotlin/org/koin/core/annotation/CoreAnnotations.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinGenerator.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/KoinMetaData.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/KspExt.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/verify/Ignored.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/verify/KoinConfigVerification.kt
Fix configuration check about ignored type list (Android) or if the type nullable.
Introduce `@Provided` to let define a dependency as provided externally to Koin annotations config. Like if you have a type declared manually in DSL ou on the fly, you can unlock Koin config check to verify it.
example:
```kotlin
@Factory
class MyPresenter(val context: Context, @Provided val provided : MyProvidedComponent)
```
Context: is detected as ignored type to verify
MyProvidedComponent: is tagged as provided externally
> Config check for ignored types, nullable and provided type

- examples/other-ksp/src/main/kotlin/org/koin/example/newmodule/ComponentWithDefaultValues.kt
- examples/other-ksp/src/test/kotlin/org.koin.example/TestModule.kt
- projects/koin-annotations/src/commonMain/kotlin/org/koin/core/annotation/CoreAnnotations.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/DefinitionGenerationExt.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/KoinMetaData.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/KoinMetaDataScanner.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/KspExt.kt
Koin Annotations offers you the possibility to define a default value for a property, directly from your code with `@PropertyValue` annotation.
Let's follow our sample:
```kotlin
@Factory
public class ComponentWithProps(
@Property("id") public val id : String
){
public companion object {
@PropertyValue("id")
public const val DEFAULT_ID : String = "_empty_id"
}
}
```
The generated DSL equivalent will be `factory { ComponentWithProps(getProperty("id", ComponentWithProps.DEFAULT_ID)) }`
Fix #73
> Property value to define value for Property in code

- docs/setup/annotations.md
- examples/gradle/libs.versions.toml
- projects/gradle.properties
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/DefinitionGenerationExt.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/ModuleGenerationExt.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/KoinMetaData.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/ClassComponentScanner.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/FunctionScanner.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/ModuleScanner.kt
Skipping code generation if module or definition comes from expect class/fun
> RC3 - fix skip is expect

- docs/reference/koin-annotations/definitions.md
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/KspOptions.kt
Add KOIN_USE_COMPOSE_VIEWMODEL key to replace USE_COMPOSE_VIEWMODEL
> Add KOIN_USE_COMPOSE_VIEWMODEL key to replace USE_COMPOSE_VIEWMODEL

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
The warning below is still shown when `KOIN_USE_COMPOSE_VIEWMODEL` arg is used.
```
w: [ksp] [Deprecated] 'USE_COMPOSE_VIEWMODEL' arg is deprecated. Please use 'KOIN_USE_COMPOSE_VIEWMODEL'
w: [ksp] Activate Compose ViewModel for @KoinViewModel generation
```
I see the `USE_COMPOSE_VIEWMODEL` is to be deprecated after Koin 4.0, so I am not sure if this PR is really viable...we can close it if not.
> Fix warning args warning

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/AnnotationMetadata.kt
Hey @arnaudgiuliani , the import generated when `KOIN_USE_COMPOSE_VIEWMODEL` is active is `org.koin.compose.viewmodel.dsl.viewModel` which is unresolved and throws an error `Unresolved reference 'viewmodel'.` 
.Also from the warning when the above argument is inactive says the import should be from `org.koin.core.module.dsl.*`
```
@Deprecated("Moved ViewModel DSL package. Remove old imports and use org.koin.core.module.dsl.*
```
Potential fix for #171
> Fix compose import

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/verify/KoinTagWriter.kt
Thanks for sharing this ksp compiler, it really helps our development. 🤝 
I found that `OutputStream` instances created by `writeTagFile()` are not closed, so here I want to suggest a small fix.
I will create another PR to make this KSP compiler [reproducible](https://reproducible-builds.org/), but first please review this small PR.
> Close OutputStream created by `writeTagFile()`

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/verify/KoinTagWriter.kt
Current implementation decides the name of `KoinMeta` file randomly, and it makes the build not reproducible. In other words, `kspKotlin` task generates different output even when input is same.
By this behaviour, Gradle tasks depending on the generated `KoinMeta` file like `compileKotlin` are executed even though no code has been changed. I will share screenshot of Gradle build scan for reference:
I want to suggest this change to stabilize name of the `KoinMeta` file. By this change, koin-ksp-compiler will compute digest of generated file, then use it to name the `KoinMeta` file. It will make the `kspKotlin` task reproducible, and make successor tasks able to use build cache.
> Realize Reproducible Builds by stabilize name of the `KoinMeta` file

- README.md
- docs/reference/koin-annotations/definitions.md
- examples/other-ksp/src/main/kotlin/org/koin/example/animal/Animal.kt
- examples/other-ksp/src/test/kotlin/org.koin.example/TestModule.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/ext/KspExt.kt
Following #108, I was wondering if it was possible to improve class-based qualifiers even more by being able to make our own qualifier annotations like so:
```kotlin
@Named
annotation class InMemoryLogger
@Named
annotation class DatabaseLogger
@Single
@InMemoryLogger
class LoggerInMemoryDataSource : LoggerDataSource
@Single
@DatabaseLogger
class LoggerLocalDataSource(private val logDao: LogDao) : LoggerDataSource
```
These dependencies would be injected that way:
```kotlin
val logger: LoggerDataSource by inject(named<InMemoryLogger>())
```
They would also be injected into constructors using the same annotation.
I think the syntax looks better that way but not everyone may think the same. Regardless, I feel like it wouldn't be a bad idea to give the developer the ability to choose between …
> feat: allow creating custom qualifier annotations

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/KoinMetaDataScanner.kt
This fixes #132 by removing any state storage between different rounds
> Remove internal scan state from Symbol Scanning

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/KspOptions.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinCodeGenerator.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/ModuleWriter.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/AnnotationMetadata.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/ClassComponentScanner.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/FunctionScanner.kt
Clean up old code for ViewModel generation to take Koin 4.0 default ViewModel API.
Allow to keep it by default to true. can be disabled
> ViewModel generation default to Koin 4.0

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/metadata/KoinMetaData.kt
Both `packageName` and `simpleName` are of the type `KSNameImpl` which does not override the `toString` properly, thus returning the standard JVM `the.library.package.MyClass@13371337` output.
Looking through the KSP code, I can't seem to find any indication that this previously implicitly used `toString` ever returned the correct output. Thus, I'm fixing it and expecting no breaking changes caused by old KSP versions.
Before:
After:
Let me know if the interest in a Backport exists.
> fix: `Scope.getValue` returns KSP type name

- examples/other-ksp/src/main/kotlin/org/koin/example/animal/Animal.kt
- examples/other-ksp/src/test/kotlin/org.koin.example/TestModule.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/scanner/ext/KspExt.kt
Following #176, after some testing on v2.0.0-Beta3, I found that the custom qualifier annotations do not generate the qualifier when used to inject a parameter, which would in most cases cause a `NoDefinitionFoundException` at runtime.
This PR addresses the issue by correctly generating the corresponding qualifier.
Example:
```kotlin
@Named
public annotation class WhiteBunny
@Qualifier
public annotation class BlackBunny
@Single
public class Farm(@WhiteBunny public val whiteBunny: Bunny, @BlackBunny public val blackBunny: Bunny)
```
Generated code before fix:
```kotlin
single() { _ -> org.koin.example.animal.Farm(whiteBunny=get(),blackBunny=get()) }
```
Generated code after fix:
```
single() { _ -> org.koin.example.animal.Farm(whiteBunny=get(qualifier=org.koin.core.qualifier.StringQualifier …
```
> fix: custom qualifier annotations not generating qualifier at injection point

- examples/compile-perf/build.gradle.kts
- examples/compile-perf/src/main/kotlin/org/koin/example/PerfApp.kt
- examples/compile-perf/src/main/kotlin/org/koin/example/components/four/AllComponents4.kt
- examples/compile-perf/src/test/java/PerfAppTest.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinCodeGenerator.kt
- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/ModuleWriter.kt
split module generation if goes over 500, into submodules.
Keep main modules to include regular includes, external definitions and new generated submodules.
> Feature - split module generation if goes over 500

- projects/koin-annotations/src/commonMain/kotlin/org/koin/core/annotation/CoreAnnotations.kt
I realized I made a mistake in my previous PR (#131) regarding the doc string for the `ComponentScan` annotation. This PR updates the docs to be more understandable.
The key point is that the previous docs implied that `com.example.**` would also scan `com.example` itself, but that's not the case—it only scans all underlying packages.
Thanks for your understanding and feedback!
> Improve docs for `ComponentScan`

- projects/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/verify/KoinConfigChecker.kt
Now detects all cycles in the dependency graph, not just those back to the origin:
1. Finds the cycle start point using indexOf()
2. Extracts only the cyclic portion with subList()
3. Reports the actual cycle path instead of the full traversal path
Example:
- Before: Only reported A -> B -> C -> A
- After: Also reports intermediate cycles like B -> C -> D -> B
Delivered in release `2.1.1-Beta1`
> Fix cycle detection up and down
